### ISSUE TITLE
Please add license information

### ISSUE THREAD

**Issue by IzzySoft** [AndreyPavlenko/transmissionbtc#10]
I've checked the ReadMe and even skimmed the code, but could find no information what license the sources are protected by. Could you please clarify? Thanks in advance!

**Comment by IzzySoft** [comment]
PS: While on it, could you please also tag v1.3.3 which you already published to Google Play and attach its APK?

**Comment by IzzySoft** [comment]
@AndreyPavlenko any chance?

**Comment by AndreyPavlenko** [comment]
Sorry, forgot about this case.
Since it's based on the Transmission code base, which is licensed under GPL, I have to follow GPL restrictions. Thus, the license is GPLv2.

**Comment by IzzySoft** [comment]
Thanks Andrey! May I suggest adding the corresponding `LICENSE.txt` to the root of your project (to the root because that's were Github does automatically recognize it)? And may I also renew my request for the tag of the latest release, with its corresponding APK attached? Thanks a lot!

**Comment by AndreyPavlenko** [comment]
I've committed the license. I'll upload the apks with the new version. Currently I'm unable to build apks - build failed for some reason, but I don't have time at the moment for the fix.

**Comment by IzzySoft** [comment]
Thanks again! Please give me a ping here when the APK is ready – and best wishes to get the build issues done, as well as all those things eating your time currently!

**Comment by AndreyPavlenko** [comment]
Sorry, forgot to ping you. The apk has been published.

**Comment by IzzySoft** [comment]
Thanks! Update picked and configuration adjusted. If you want to add some nice badges to your Readme, [find them here](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) and [link them here](https://apt.izzysoft.de/fdroid/index/apk/com.ap.transmission.btc); the new version should show up with the next sync tomorrow, and future ones within 24h of your making them available.
