### ISSUE TITLE
files allocation

### ISSUE THREAD

**Issue by z3huti** [AndreyPavlenko/transmissionbtc#12]
При добавление торрента через RPC

1. добавляем торрент но не запускаем его сразу
2. убираем все галочки со всех файлов в торенте
3. выбираем один файл для скачивания. только не первый файл
4. запускаем скачивание

что происходит дальше

файл который стоит ДО выбраного файла в торенте, его размер будет полностью помечен на диске 

а если это файл размером 10GB - это же *№;%:?*

файл который стоит ПОСЛЕ выбраного файла в торенте, тоже помеченается на диске но не полностью

**Comment by AndreyPavlenko** [comment]
Да, это известная проблема Transmission. Торрент разбит на равные части, каждая часть скачивается полностью. Если в одной части содержится конец и начало двух файлов, то создаются оба файла.

**Comment by z3huti** [comment]
это просто п****ц. 13 лет прошло и ничего не изменилось

думал сразу качать на андроид тв чтоб файлы лишний раз не гонять по wifi с компа, но нет блин =)

у BiglyBT еще хуже.  если выбрать только один файл, то он все файлы из торрента помеченает на диске, програмеры хреновы =)
