### ISSUE TITLE
android tv and boot at start

### ISSUE THREAD

**Issue by userofryzen** [AndreyPavlenko/transmissionbtc#14]
In my android TV transmission doesn't start at boot while biglybt in the same device yes. So I suppose that it has to be a problem specific from this program and not device specific. 

Buglybt android version is open source I think so probably you can have a look at the code to see what It does specifically.

**Comment by userofryzen** [comment]
When will the version 1.3.6 that is on the commits get out on play store?

**Comment by userofryzen** [comment]
Thanks for the quick response and solutions by the way!

**Comment by AndreyPavlenko** [comment]
I've already uploaded a testing version, but it's not yet published by google play.

**Comment by userofryzen** [comment]
Tested it with the beta tester channel. Works well. Thanks you!

**Comment by AndreyPavlenko** [comment]
Thanks. I've uploaded it to the release channel.

**Comment by userofryzen** [comment]
Updated: 
The start with the android rebooting or booting at all is fine. But if the device is in standby , when going on again the client won't start itself. Maybe is some rstriction with android tv or who knows, it's not esential to be honest but here you have the "bug" so you can decide what to do . 

To completion the info, the app is installed in a hdd that is loaded just after going on from standby( dunno why is this way...)
I have tested to put time of delay but it won't fix the problem. Someone can reproduce the problem?

**Comment by userofryzen** [comment]
when booting the device from 0( cold start) or rebooting is fine, but when standby to boot the app has to be "launched" manually

**Comment by userofryzen** [comment]
when booting the device from 0( cold start) or rebooting is fine, but when standby to boot the app has to be "launched" manually

@AndreyPavlenko can you open or maybe make another issue for this?

Thanks again

**Comment by AndreyPavlenko** [comment]
Could you attach the logcat logs?

**Comment by userofryzen** [comment]
I m not in my house in a few days. I will when I can okey?
Thanks anyway for the quick reply
