### ISSUE TITLE
DIsplay localhost's ip address

### ISSUE THREAD

**Issue by ianwong99** [AndreyPavlenko/transmissionbtc#23]
Hi Andrey,

First off, thank you so much for your work on making this clean and reliable app. I just have one suggestion: is there a way to toggle so that the setting menu show's the ip address of the device. This would make connecting to the web UI on other devices in the same network much easier.

Thank you

**Comment by AndreyPavlenko** [comment]
The ip address is shown in the notification bar, when the service is started.

**Comment by ianwong99** [comment]
Thank you! I am using a fire stick so notification is hidden. I would say definitely Amazon's fault
