### ISSUE TITLE
armeabi-v7a support

### ISSUE THREAD

**Issue by zhuangyy** [AndreyPavlenko/transmissionbtc#4]
Would you please add armeabi-v7a support in next apk release? A lot of tvboxs, including mine, are still running as arm32.
Thanks.

**Comment by AndreyPavlenko** [comment]
armeabi-v7a is supported - https://github.com/AndreyPavlenko/transmissionbtc/blob/65bfc183ca1893a0020d152493d3f2b5180ce68b/build.gradle#L27

**Comment by zhuangyy** [comment]
but not included in apk? only arm64-v8a can be found in apk downloaded from google-play

![image](https://user-images.githubusercontent.com/2098554/57012440-1bfcd180-6c39-11e9-9a1e-793fa2449e9b.png)

**Comment by AndreyPavlenko** [comment]
The build produces 5 apks for different platforms:
com.ap.transmission.btc-android_4.1-arm-1.3.2.apk 
com.ap.transmission.btc-android_5.0-arm-1.3.2.apk
com.ap.transmission.btc-android_5.0-x86_64-1.3.2.apk 
com.ap.transmission.btc-android_4.1-x86-1.3.2.apk
com.ap.transmission.btc-android_5.0-arm64-1.3.2.apk

Google play has all these versions, but only the matching version is downloaded.

**Comment by zhuangyy** [comment]
thanks very much for your quick reply, that resolved my doubts. by googling I can find a download link for the apk above in a Russian web site but leads to a 404 error. 

still can not figure out how to download apk from google play with specified platform (a chrome extension named apk downloader is used).

would you please publish those apks as releases in this github repository, so this apk can be downloaded and installed on devices which have no access to google play.

**Comment by AndreyPavlenko** [comment]
Published.
