### ISSUE TITLE
Settings tab is empty on Androd 7

### ISSUE THREAD

**Issue by roman-rybalko** [AndreyPavlenko/transmissionbtc#6]
Android 7.1.2 on Rockchip RK3328 (armv8).
Setting and Proxy Settings UI tabs are empty. No way to set download directories and proxy.

**Comment by AndreyPavlenko** [comment]
Can you check the logs in logcat? Perhaps there is some error.

**Comment by roman-rybalko** [comment]
Here is [logcat](https://pastebin.com/PucHQhfx).

**Comment by AndreyPavlenko** [comment]
I don't see any errors. Unfortunately I can't reproduce the issue on Android 7.1.2 device neither on emulator.

**Comment by roman-rybalko** [comment]
I have issues with `BOOT_COMPLETED` broadcast on my system. Perhaps that was the cause. Also my system does not preserve time between reboots, so it starts at 01-01-1970 so many files at boot are in future. Will address those issues first.
