### ISSUE TITLE
How to start web interface after reboot without pushing 'Start' button?

### ISSUE THREAD

**Issue by bellerofonte** [AndreyPavlenko/transmissionbtc#8]
Hi!

I have an Android TV box with Transmission BTC installed. Autostart is enabled (0 seconds delay). Unfortunately WebUI is **not** available until 'Start' button is pressed. Is it possible to make WebUI start on reboot automatically? Thanks.

**Comment by AndreyPavlenko** [comment]
Hi,

If autostart is enabled, it should start automatically. Try to increase the delay.

**Comment by bellerofonte** [comment]
@AndreyPavlenko thanks, 10 seconds delay makes WebUI start after reboot. But there is another issue. WebUI is started, but shows pop-up error:
_**Connection Failed**_
_Could not connect to the server. You may need to reload the page to reconnect._
And it still requires to click on 'Start' button to fix that issue.

**Comment by AndreyPavlenko** [comment]
What do you mean by "WebUI is started"? It starts the transmission service, WebUI is just an interface. If the service is started and then stopped, perhaps it's stopped by the system.

**Comment by bellerofonte** [comment]
I mean following:
- Autostart is enabled in settings, delay is 10 seconds (tried values 0 to 30 - the same effect)
- Reboot TV box
- Go to WebUI in browser - UI works, shows an error as described above
- OK, may be WebUI is cached in browser? Trying `curl -v 'http://tv-box-ip:9091/` -  gets HTTP 301. Trying `curl -v 'http://tv-box-ip:9091/transmission/web` - gets another HTTP response with some HTML. So 100% WebUI is served from TV box.
- But I can neither get active torrents nor add/remove them until I go to the app on TV box and push 'Start' button.

**Comment by AndreyPavlenko** [comment]
It's strange, because if the service is running the Start button should be inactive.
What's the HTML you are getting from http://tv-box-ip:9091/transmission/web ? Is it something like "Your request had an invalid session-id header"?

**Comment by bellerofonte** [comment]
> Is it something like "Your request had an invalid session-id header"?

Yes, exactly.

**Comment by AndreyPavlenko** [comment]
Can you try some transmission remote app or the command line client?
E.g.: transmission-remote tv-box-ip -l

**Comment by bellerofonte** [comment]
@AndreyPavlenko thanks for your help. Solved problem by disabling battery saving for Transmission app in Android settings.
P.S. transmission-remote did not connect (as intended) until server is actually started.
